- name: Play-01
  hosts: web #which hosts your ansible wants to connect
  vars_files:
  - vars.yaml
  tasks: #list of tasks/modules/collections
  - name: ping the server
    ansible.builtin.debug:
      msg: "Name is {{NAME}}"
  - name: ping the server
    ansible.builtin.debug:
      msg: "Name is {{NAME}}"
  - name: ping the server
    ansible.builtin.debug:
      msg: "Name is {{NAME}}"
