- name: check the prompt number is greater than 10 or not
  hosts: local
  connection: local
  vars_prompt:
    - name: my_number
      prompt: Enter the number
      private: false
  tasks:
  - name: checking the given number is greater than 10 or not
    ansible.builtin.debug:
      msg: "given number: {{my_number}} is greater than or equal to 10"
    when: my_number | int >= 10
  - name: checking the number is lesser than or equal to 10
    ansible.builtin.debug:
      msg: "given number is {{my_number}} is lesser than 10"
    when: my_number | int<10