- name: installing mysql, nodejs and nginx
  hosts: web
  become: yes
  tasks:
  - name: installing with loops
    ansible.builtin.package:
      name: "{{item}}"
      state: present
    loop:
    - mysql
    - nodejs
    - nginx