- name: working on functions
  hosts: local
  connection: local
  tasks:
  - name: working on default functions
    ansible.builtin.debug:
      msg: " Hi {{ Name | default('Manohar')}}"
  - name: working on upper filter
    vars:
      Name: "Manohar"
    ansible.builtin.debug:
      msg: "My name is {{ Name | upper }}"
  - name: working on lower filter
    vars:
      Name: "Manohar"
    ansible.builtin.debug:
      msg: "My name is {{ Name | lower }}"
  - name: working on get unque numbers in a list
    vars:
      numbers: [1,2,3,4,3,2,1,5]
    ansible.builtin.debug:
      msg: "unique numbers are {{ numbers | unique }}"

