- name: working on functions
  hosts: local
  connection: local
  tasks:
  - name: working on default functions
    ansible.builtin.debug:
      msg: " Hi {{ Name | default('Manohar')}}"
  - name: working on upper filter
    vars:
      Name: "Manohar"
    ansible.builtin.debug:
      msg: "My name is {{ Name | upper }}"
  - name: working on lower filter
    vars:
      Name: "Manohar"
    ansible.builtin.debug:
      msg: "My name is {{ Name | lower }}"
  - name: working on get unque numbers in a list
    vars:
      numbers: [1,2,3,4,3,2,1,5]
    ansible.builtin.debug:
      msg: "unique numbers are {{ numbers | unique }}"

  - name: getting minimum number in list
    vars:
      numbers: [1,2,3,4,0,-1]
    ansible.builtin.debug:
      msg: "Minimum number is :{{ numbers | min }}"
  - name: getting maximum number in list
    vars:
      numbers: [1,2,3,4,0,-1]
    ansible.builtin.debug:
      msg: "Maximum number is :{{ numbers | max }}"

  - name: convert maps to list
    vars:
      course:
        Name: "Devops"
        duration: 120
    ansible.builtin.debug:
      msg: "maps to list is {{ course | dict2items }}"

  - name: list to maps
    vars:
      course: 
        - {'key': 'Name', 'value': 'Devops'}
        - {'key': 'duration', 'value': 120}
    ansible.builtin.debug:
      msg: " Maps are :{{course | items2dict}}"
  - name: check the ip address isvvalid or not 
    vars_promt:
      ip_address: "182.12.13.14"
    ansible.builtin.debug:
      msg: " Ip address is : {{ ip_address  | ansible.utils.ipv4}}"


