- name: creating ec2 and r53 instances
  hosts: local
  connection: local
  vars:
    subnet_id: subnet-04dfeee3b9049b490
    sg_id: "sg-0ae1aad22a8b34c76"
    ami_id: "ami-09c813fb71547fc4f"
    servers:
    - mysql
    - backend
    - frontend
  tasks:
  - name: ansible to install boto3 and botocore
    ansible.builtin.pip:
      name:
      - boto3
      - botocore
      executable: pip3.9
  - name: creating ec2 instances
    amazon.aws.ec2_instance:
      name: "{{ item }}"
      vpc_subnet_id: "{{ subnet_id }}"
      instance_type: "t3.micro"
      security_group: "{{ sg_id }}"
      image_id: "{{ ami_id }}"
    loop: "{{ servers }}"
    register: ec2_instances
